CREATE DATABASE partydb;


create table users (
	user_id INT,
	first_name VARCHAR(50),
	department VARCHAR(50)
);
insert into users (user_id, first_name, department) values (1, 'Melantha', 'Human Resources');
insert into users (user_id, first_name, department) values (2, 'Gilberte', 'Legal');
insert into users (user_id, first_name, department) values (3, 'Willey', 'Research and Development');
insert into users (user_id, first_name, department) values (4, 'Tybi', 'Sales');
insert into users (user_id, first_name, department) values (5, 'Bryant', 'Engineering');
insert into users (user_id, first_name, department) values (6, 'Bud', 'Marketing');
insert into users (user_id, first_name, department) values (7, 'Eddie', 'Training');
insert into users (user_id, first_name, department) values (8, 'Karlen', 'Research and Development');
insert into users (user_id, first_name, department) values (9, 'Carla', 'Support');
insert into users (user_id, first_name, department) values (10, 'Guenevere', 'Business Development');
insert into users (user_id, first_name, department) values (11, 'Noni', 'Training');
insert into users (user_id, first_name, department) values (12, 'Jeffry', 'Business Development');
insert into users (user_id, first_name, department) values (13, 'Licha', 'Human Resources');
insert into users (user_id, first_name, department) values (14, 'Bessy', 'Support');
insert into users (user_id, first_name, department) values (15, 'Garek', 'Sales');
insert into users (user_id, first_name, department) values (16, 'Paula', 'Engineering');
insert into users (user_id, first_name, department) values (17, 'Birch', 'Accounting');
insert into users (user_id, first_name, department) values (18, 'Joella', 'Sales');
insert into users (user_id, first_name, department) values (19, 'Jean', 'Engineering');
insert into users (user_id, first_name, department) values (20, 'Yvette', 'Product Management');
insert into users (user_id, first_name, department) values (21, 'Rosina', 'Product Management');
insert into users (user_id, first_name, department) values (22, 'Bellanca', 'Product Management');
insert into users (user_id, first_name, department) values (23, 'Mirabelle', 'Research and Development');
insert into users (user_id, first_name, department) values (24, 'Zane', 'Human Resources');
insert into users (user_id, first_name, department) values (25, 'Christalle', 'Services');
insert into users (user_id, first_name, department) values (26, 'Madalyn', 'Product Management');
insert into users (user_id, first_name, department) values (27, 'Charo', 'Services');
insert into users (user_id, first_name, department) values (28, 'Allissa', 'Research and Development');
insert into users (user_id, first_name, department) values (29, 'Giavani', 'Training');
insert into users (user_id, first_name, department) values (30, 'West', 'Engineering');
insert into users (user_id, first_name, department) values (31, 'Alford', 'Research and Development');
insert into users (user_id, first_name, department) values (32, 'Fons', 'Human Resources');
insert into users (user_id, first_name, department) values (33, 'Bonnie', 'Product Management');
insert into users (user_id, first_name, department) values (34, 'Donelle', 'Product Management');
insert into users (user_id, first_name, department) values (35, 'Birdie', 'Engineering');
insert into users (user_id, first_name, department) values (36, 'Grove', 'Legal');
insert into users (user_id, first_name, department) values (37, 'Noam', 'Support');
insert into users (user_id, first_name, department) values (38, 'Jammal', 'Support');
insert into users (user_id, first_name, department) values (39, 'Harris', 'Legal');
insert into users (user_id, first_name, department) values (40, 'Rene', 'Human Resources');
insert into users (user_id, first_name, department) values (41, 'Josefina', 'Training');
insert into users (user_id, first_name, department) values (42, 'Camella', 'Training');
insert into users (user_id, first_name, department) values (43, 'Darbie', 'Legal');
insert into users (user_id, first_name, department) values (44, 'Cristi', 'Marketing');
insert into users (user_id, first_name, department) values (45, 'Kandace', 'Services');
insert into users (user_id, first_name, department) values (46, 'Fanya', 'Training');
insert into users (user_id, first_name, department) values (47, 'Jodie', 'Product Management');
insert into users (user_id, first_name, department) values (48, 'Hardy', 'Training');
insert into users (user_id, first_name, department) values (49, 'Marlowe', 'Accounting');
insert into users (user_id, first_name, department) values (50, 'Claudianus', 'Marketing');
insert into users (user_id, first_name, department) values (51, 'Dorine', 'Research and Development');
insert into users (user_id, first_name, department) values (52, 'Brod', 'Product Management');
insert into users (user_id, first_name, department) values (53, 'Cos', 'Marketing');
insert into users (user_id, first_name, department) values (54, 'Stefanie', 'Accounting');
insert into users (user_id, first_name, department) values (55, 'Deeyn', 'Human Resources');
insert into users (user_id, first_name, department) values (56, 'Delano', 'Accounting');
insert into users (user_id, first_name, department) values (57, 'Val', 'Accounting');
insert into users (user_id, first_name, department) values (58, 'Jacquelynn', 'Human Resources');
insert into users (user_id, first_name, department) values (59, 'Candis', 'Business Development');
insert into users (user_id, first_name, department) values (60, 'Ferdie', 'Accounting');
insert into users (user_id, first_name, department) values (61, 'Latrina', 'Services');
insert into users (user_id, first_name, department) values (62, 'Ritchie', 'Sales');
insert into users (user_id, first_name, department) values (63, 'Kari', 'Business Development');
insert into users (user_id, first_name, department) values (64, 'Stefanie', 'Human Resources');
insert into users (user_id, first_name, department) values (65, 'Hyman', 'Legal');
insert into users (user_id, first_name, department) values (66, 'Elvyn', 'Product Management');
insert into users (user_id, first_name, department) values (67, 'Erhard', 'Legal');
insert into users (user_id, first_name, department) values (68, 'Tova', 'Accounting');
insert into users (user_id, first_name, department) values (69, 'Chiarra', 'Sales');
insert into users (user_id, first_name, department) values (70, 'Evelyn', 'Training');
insert into users (user_id, first_name, department) values (71, 'Bevon', 'Services');
insert into users (user_id, first_name, department) values (72, 'Ekaterina', 'Services');
insert into users (user_id, first_name, department) values (73, 'Lorilyn', 'Engineering');
insert into users (user_id, first_name, department) values (74, 'Vitia', 'Legal');
insert into users (user_id, first_name, department) values (75, 'Osgood', 'Legal');
insert into users (user_id, first_name, department) values (76, 'Coleen', 'Support');
insert into users (user_id, first_name, department) values (77, 'Calla', 'Marketing');
insert into users (user_id, first_name, department) values (78, 'Salomo', 'Research and Development');
insert into users (user_id, first_name, department) values (79, 'Esma', 'Sales');
insert into users (user_id, first_name, department) values (80, 'Althea', 'Training');
insert into users (user_id, first_name, department) values (81, 'Muffin', 'Training');
insert into users (user_id, first_name, department) values (82, 'Hussein', 'Support');
insert into users (user_id, first_name, department) values (83, 'Lidia', 'Accounting');
insert into users (user_id, first_name, department) values (84, 'Corly', 'Sales');
insert into users (user_id, first_name, department) values (85, 'Giovanni', 'Research and Development');
insert into users (user_id, first_name, department) values (86, 'Constantin', 'Marketing');
insert into users (user_id, first_name, department) values (87, 'Evey', 'Human Resources');
insert into users (user_id, first_name, department) values (88, 'Jarret', 'Business Development');
insert into users (user_id, first_name, department) values (89, 'Les', 'Services');
insert into users (user_id, first_name, department) values (90, 'Frannie', 'Accounting');
insert into users (user_id, first_name, department) values (91, 'Palmer', 'Sales');
insert into users (user_id, first_name, department) values (92, 'Griffith', 'Accounting');
insert into users (user_id, first_name, department) values (93, 'Bibbye', 'Business Development');
insert into users (user_id, first_name, department) values (94, 'Tiffie', 'Business Development');
insert into users (user_id, first_name, department) values (95, 'Valdemar', 'Human Resources');
insert into users (user_id, first_name, department) values (96, 'Lilli', 'Accounting');
insert into users (user_id, first_name, department) values (97, 'Aubrette', 'Research and Development');
insert into users (user_id, first_name, department) values (98, 'Rosene', 'Product Management');
insert into users (user_id, first_name, department) values (99, 'Galvan', 'Research and Development');
insert into users (user_id, first_name, department) values (100, 'Cornell', 'Legal');
